### ISSUE TITLE
any help with a example? 

### ISSUE THREAD

**Issue by moebiussurfing** [jaysonh/ofxFontThreeDee#1]
hey @jaysonh , thanks for sharing.
(I found https://gist.github.com/vvzen/9315c7658e96955af593bec74bc3508a too.)
I am trying to test it but no success. Can you share an example?

That's what I am trying:

```.cpp
ofApp.h
ofxFontThreeDee extruder;
vector<ofVboMesh> my_extruded_word;

ofApp.cpp
void ofApp::setup() {
	//font.load("verdana.ttf", 50);
	extruder.load("verdana.ttf", 50);
	string word = "LOST";

	my_extruded_word = extruder.extrude_mesh_from_text(word, 50);
}

void ofApp::draw() {
	for (int m = 0; m < my_extruded_word.size(); m++) {
		my_extruded_word.at(m).draw();
	}
}
```

And the error that I get:
![Capture](https://user-images.githubusercontent.com/2106149/83409521-f23d4d80-a3ea-11ea-817b-1aaf03b53b4f.PNG)

**Comment by jaysonh** [comment]
Maybe you don't have the correct .ttf font file in the data folder. Are you loading a font ok in setup()?

Since it extends ofTrueTypeFont you need to call .loadFont() in setup first before using this. I'll upload an example

**Comment by moebiussurfing** [comment]
hey, I found the problem. must load the font with some of these other arguments:
```.cpp
extruder.load("verdana.ttf", 50, true, true, true);
```
